---
apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: k8s-home-lab-repo
  namespace: home-assistant
spec:
  interval: 1m
  url: https://k8s-home-lab.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 1m
  #targetNamespace: home-assistant
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: k8s-home-lab-repo
  values:
    global:
      addons.codeserver: true
      image:
        repository: ghcr.io/home-assistant/home-assistant
        tag: latest # replace with the latest version

--- 
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-balancer
  namespace: home-assistant
spec:
  selector:
    app.kubernetes.io/name: home-assistant
    #name: home-assistant
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
---