---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: DeepDeploy
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Deepdelver/DeepsLab
    targetRevision: HEAD
    path: DeepDeploy
  destination:
    server: https://kubernetes.default.svc
    namespace: deepdeploy
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
